config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  resources :dogs

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: "users/sessions", passwords: 'users/passwords' } do
     get "/", :to => "users/sessions#create"
   end

   authenticated :user do
     root to: "dogs#mydogs"
   end

   unauthenticated :user do
     devise_scope :user do
       get "/" => "home#homepage"
     end
   end

  get 'mydogs', to: 'dogs#mydogs'
  get 'dogs/:id/compare', to: 'dogs#compare', as: :dog_compare
  get 'allfavorites', to: 'dogs#allfavorites'
  get 'advancedsearch', to: 'dogs#advancedsearch'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dog.rb
class Dog < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :delete_all
  validates :gender,  presence: true

  BREEDS =
   ['Affenpinscher',
    'Afghan Hound',
    'Airedale Terrier',
    'Akita',
    'Akita Americano',
    'American Pit Bull Terrier',
    'American Staffordshire Terrier',
    'Australian Shepherd',
    'Basenji',
    'Basset Fulvo da Bretanha',
    'Basset Hound',
    'Beagle',
    'Beagle-Harrier',
    'Bearded Collie',
    'Bedlington Terrier',
    'Bernese Mountain Dog',
    'Bichon Bolonhês',
    'Bichon Frisé',
    'Bichon Havanês',
    'Boerboel',
    'Boiadeiro de Entlebuch',
    'Border Collie',
    'Border Terrier',
    'Borzoi',
    'Boston Terrier',
    'Bouvier de Flandres',
    'Boxer',
    'Braco Alemão Pelo Curto',
    'Braco Alemão Pelo Duro',
    'Braco Italiano',
    'Buldogue Americano',
    'Buldogue Francês',
    'Buldogue Inglês',
    'Bull Terrier',
    'Bullmastiff',
    'Cairn Terrier' ,
    'Cane Corso',
    'Cão de Crista Chinês',
    'Cão de  Santo Humberto',
    "Cão D’água Espanhol",
    "Cão D’água Português",
    'Cão Lobo Checoslovaco',
    'Cão Pelado Mexicano',
    'Cão Pelado Peruano',
    'Cavalier King Charles Spaniel',
    'Cesky Terrier',
    'Chesapeake Bay Retriever',
    'Chihuahua',
    'Chin',
    'Chow-chow Pelo Curto',
    'Chow-chow Pelo Longo',
    'Cirneco do Etna',
    'Clumber Spaniel',
    'Cocker Spaniel Americano',
    'Cocker Spaniel Inglês',
    'Collie pelo longo',
    'Coton de Tulear',
    'Dachshund Teckel - Pelo Curto',
    'Dálmata',
    'Dandie Dinmont Terrier',
    'Dobermann',
    'Dogo Argentino',
    'Dogo Canário',
    'Dogue Alemão',
    'Dogue de Bordeaux',
    'Elkhound Norueguês Cinza',
    'Fila Brasileiro',
    'Flat-Coated Retriever',
    'Fox Terrier Pelo Duro',
    'Fox Terrier Pelo Liso',
    'Foxhound Inglês',
    'Galgo Espanhol',
    'Golden Retriever',
    'Grande Münsterländer',
    'Greyhound',
    'Griffon Belga',
    'Griffon de Bruxelas',
    'Husky Siberiano',
    'Ibizan Hound',
    'Irish Soft Coated Wheaten Terrier',
    'Irish Wolfhound',
    'Jack Russell Terrier',
    'Kerry Blue Terrier',
    'Komondor',
    'Kuvasz',
    'Labrador Retriever',
    'Lagotto Romagnolo',
    'Lakeland Terrier',
    'Leonberger',
    'Lhasa Apso',
    'Malamute do Alasca',
    'Maltês',
    'Mastiff',
    'Mastim Espanhol',
    'Mastino Napoletano',
    'Mudi',
    'Nordic Spitz',
    'Norfolk Terrier',
    'Norwich Terrier',
    'Old English Sheepdog',
    'Papillon',
    'Parson Russell Terrier',
    'Pastor Alemão',
    'Pastor Beauceron',
    'Pastor Belga',
    'Pastor Bergamasco',
    'Pastor Branco Suíço',
    'Pastor Briard',
    'Pastor da Ásia Central',
    'Pastor de Shetland',
    'Pastor dos Pirineus',
    'Pastor Maremano Abruzês',
    'Pastor Polonês',
    'Pastor Polonês da Planície',
    'Pequeno Basset Griffon da Vendéia',
    'Pequeno Cão Leão',
    'Pequeno Lebrel Italiano',
    'Pequinês',
    'Perdigueiro Português',
    'Petit Brabançon',
    'Pharaoh Hound',
    'Pinscher Miniatura',
    'Podengo Canário',
    'Podengo Português',
    'Pointer Inglês',
    'Poodle Anão',
    'Poodle Médio',
    'Poodle Standard',
    'Poodle Toy',
    'Pug',
    'Puli',
    'Pumi',
    'Rhodesian Ridgeback',
    'Rottweiler',
    'Saluki',
    'Samoieda',
    'São Bernardo',
    'Schipperke',
    'Schnauzer',
    'Schnauzer Gigante',
    'Schnauzer Miniatura',
    'Scottish Terrier',
    'Sealyham Terrier',
    'Setter Gordon',
    'Setter Inglês',
    'Setter Irlandês Vermelho',
    'Setter Irlandês Vermelho e Branco',
    'Shar-pei',
    'Shiba',
    'Shih-Tzu',
    'Silky Terrier Australiano',
    'Skye Terrier',
    'Smoushond Holandês',
    'Spaniel Bretão',
    'Spinone Italiano',
    'Spitz Alemão Anão',
    'Spitz Finlandês',
    'Spitz Japonês Anão',
    '(SRD)Sem Raça Definida',
    'Springer Spaniel Inglês',
    'Stabyhoun',
    'Staffordshire Bull Terrier',
    'Terra Nova',
    'Terrier Alemão de caça Jagd',
    'Terrier Brasileiro',
    'Terrier Irlandês de Glen do Imaal',
    'Terrier Preto da Rússia',
    'Tibetan Terrier',
    'Tosa Inu',
    'Vira-Latas',
    'Vizsla',
    'Volpino Italiano',
    'Weimaraner',
    'Welsh Corgi Cardigan',
    'Welsh Corgi Pembroke',
    'Welsh Springer Spaniel',
    'Welsh Terrier',
    'West Highland White Terrier',
    'Whippet',
    'Yorkshire Terrier']
    # Fonte: CachorroGato @ https://www.cachorrogato.com.br/racas-caes/

  PELAGES = [
    'Pelo curto',
    'Pelo longo',
    'Pelo encaracolado',
    'Pelagem dupla',
    'Pelo longo e curto'
  ]

  SIZES =[
    'Mini ou Toy',
    'Pequeno ou Anão',
    'Médio ',
    'Grande',
    'Gigante'
  ]


    def  vacined
      return "Sim" if self.vacine == true
      return "Não " if self.vacine == false
    end

    def  pedigre
      return "Sim" if self.pedigree == true
      return "Não" if self.vacine == false
    end

      # comparação
    # 1 Sexo diferentes
    # 2 Mesma Raça
    # 3 vacinado Igual
    # 4 Pedigre Igual
    # 5 Cor de Pelo Igual
    # 6 idade mais próxima
    # 7 peso mais próximo
    # 8 tamanho proximo


end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy, :compare]
  before_action :authenticate_user!
  before_action :authorize_dog, only: [:edit, :update, :destroy]
  # GET /dogs
  # GET /dogs.json

  layout "application"



  def index
    @Search = Dog.where.not(user_id: current_user).ransack(params[:q])
    @dogs = @Search.result(distinct: true)
    #@dogs = Dog.where.not(user_id: current_user)
  end
   # falta finalizar
  def compare
    # @dogs = Dog.where(breed: @dog.breed)
    # @dogs = Dog.ransack(breed: @dog.breed)

    @search = Dog.ransack({ breed_eq: @dog.breed, gender_not_eq: @dog.gender, vacine_eq: @dog.vacine, pedigree_eq: @dog.pedigree, user_id_not_eq: current_user.id })
    @query = @search.result.to_sql
    @dogs = @search.result
    #code
  end

  def mydogs
    @dogs = Dog.where(user_id: current_user)
  end

  def advancedsearch
    @Search = Dog.where.not(user_id: current_user).ransack(params[:q])
    @dogs = @Search.result(distinct: true)
  end
  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @favorite_exists = Favorite.where(dog: @dog, user: current_user)  == [] ? false : true
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end


  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :mydogs, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :mydogs, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :breed, :user_id, :image, :age, :gender, :vacine, :pedigree,
       :mother_name, :father_name, :register, :temperament, :length, :heigth, :pelage, :pelage_color, :weight, :teste)
    end

    def authorize_dog
      authorize @dog
    end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
<div class="row">
  <fieldset>
    <legend>
        Informações Sobre o cão
    </legend>
      <%= f.input :name, wrapper_html: { class: 'm6 s12'  } %>
      <%= f.input :image, wrapper_html: { class: 'm6 s6 l6' }  %>
      <%= f.input :breed, as: :select, collection: Dog::BREEDS, wrapper_html: { class: 'm6 sl2' } %>
      <%= f.input :gender, as: :select, collection: ['Femea', 'macho'], wrapper_html: { class: 'm6 s12' } %>
      <%= f.input :age, wrapper_html: { class: 'm6 s12'} %>
      <%= f.input :temperament, wrapper_html: { class: 'm6 s6' } %>
      <%= f.input :vacine, include_blank: 'Vacina', wrapper_html: { class: 'm6 s12' } %>
  </fieldset>
</div>

<div class="row">,
  <fieldset>
    <legend>Aspectos Físicos</legend>
    <%= f.input :length,as: :select,collection: Dog::SIZES, wrapper_html: { class: 'm6 s12 l6' } %>
    <%= f.input :weight, wrapper_html: { class: 'm6 s12 l6' } %>
    <%= f.input :heigth, wrapper_html: { class: 'm6 s12 l6' } %>
    <%= f.input :pelage, as: :select, collection: Dog::PELAGES, wrapper_html: { class: 'm6 s6' } %>
    <%= f.input :pelage_color, wrapper_html: { class: 'm6 s6' } %>
  </fieldset>
</div>



<div class="row">
  <fieldset>
    <legend>Informações sobre Pedigree</legend>
    <%= f.input :pedigree, include_blank: 'Pedigree', wrapper_html: { class: 'm6 s12' } %>
    <%= f.input :mother_name, wrapper_html: { class: 'm6 s12' } %>
    <%= f.input :father_name, wrapper_html: { class: 'm6 s12' } %>
    <%= f.input :register, wrapper_html: { class: 'm6 s12' } %>
  </fieldset>
</div>

<%= f.button :submit, "Confirmar" %>
<% end %>

app/views/dogs/advancedsearch.html.erb
<h4>Busca</h4>
<div class="row">

    <legend>Dados do Cão</legend>
       <%= search_form_for @Search do |f| %>
        <div class="col s12 l6 m6">
          <% f.label :name_cont %>
          <%= f.search_field :name_cont, placeholder: "Nome"  %>
        </div>
        <div class="col s12 l6 m6">
           <% f.label :breed_cont,"Raça" %>
           <%= f.select :breed_cont, Dog::BREEDS, include_blank: 'Raça'  %>
        </div>
        <div class="col s12 l6 m6">
           <% f.label :gender_cont %>
           <%= f.select :gender_cont, ['Femea', 'macho'], include_blank: 'sexo' %>
        </div>
        <div class="col s12 l6 m6">
           <% f.label :length_cont %>
           <%= f.select :length_cont, Dog::SIZES, include_blank:'Tamanho' %>
        </div>
        <div class="col s12 l6 m6">
           <% f.label :vacine_cont %>
           <%= f.select :vacine_eq, [['Yes', true], ['No', false]], include_blank: 'Vacina' %>
        </div>
        <div class="col s12 l6 m6">
           <% f.label :pedigree_cont %>
           <%= f.select :pedigree_eq, [['Yes', true], ['No', false]], include_blank: 'Pedigree' %>
        </div>
        <div class="col s12 l6 m6">
           <% f.label :pelage_cont %>
           <%= f.select :pelage_cont, Dog::PELAGES, include_blank:'Pelagem' %>
        </div>
        <div class="col s12 l6 m6">
           <% f.label :temperament_cont %>
           <%= f.search_field :temperament_cont, placeholder: "Temperamento"  %>
        </div>

      <legend>Dados do Dono</legend>
        <div class="col s12 l6 m6">
          <% f.label :user_name_cont %>
          <%= f.search_field :user_name_cont, placeholder: "Nome"  %>
        </div>
        <div class="col s12 l6 m6">
          <% f.label :user_state_cont %>
          <%= f.select :user_state_cont, User::STATES, include_blank: 'Estado'  %>
        </div>
        <div class="col s12 l6 m6">
          <% f.label :user_city_cont %>
          <%= f.search_field :user_city_cont, placeholder: "Cidade"  %>
        </div>

        </a>
        <div class="form-actions">
          <%= f.submit "filtrar", class: "btn btn-lg btn-success btn-block" %>
          <% end %>
        </div>

app/views/dogs/alldogs.html.erb
<p id="notice"><%= notice %></p>

<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Imagem</th>
      <th>Name</th>
      <th>Breed</th>
      <th>User</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= image_tag(dog.image_url(:thumb).to_s) %></td>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.user.name %></td>
        <td><%= link_to 'Show', dog %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/dogs/allfavorites.html.erb
<div class="row">
  <% current_user.favorites.each do |favorite| %>
   <div class="col l3 m6 s6">
     <div class="card">
       <div class="card-image">
        <% if favorite.dog.image.present? %>
           <%= link_to image_tag(favorite.dog.image_url(:thumb).to_s), favorite.dog %>
           <% else %>
              <%= link_to image_tag('logo.png', size:"227x227"), favorite.dog %>
        <% end %>
       </div>
          <div class="card-content">
            <span class="card-title">
              <%= favorite.dog.name %>
            </span>
            <%= favorite.dog.gender %>
            <br>
            <%= favorite.dog.breed %>
            <br>
            <strong>Vacina  </strong>
            <%= favorite.dog.vacined %>
            <br>
            <strong>Pedigree </strong>
            <%= favorite.dog.pedigre %>
          </div>
     </div>
   </div>
      <% end %>
</div>

app/views/dogs/compare.html.erb
<h1>Compare</h1>
<p> <%= @query %> </p>
<div class="row">
    <% @dogs.each do |dog| %>
      <div class = "col l3 m6 s12">
          <div class= "card">
            <div class= "card-image">
                <%= link_to image_tag(dog.image_url(:thumb).to_s), dog %>
               <span class="card-title">
                <%= dog.name %>
                </span>
            </div>
              <div class="card-content">
                <%= dog.gender %>
                <br>
                <%= dog.breed %>
                <br>
                <strong>Vacinado</strong>
                <%= dog.vacined %>
                <br>
                <strong>Pedigree</strong>
                <%= dog.pedigre %>
              </div>
          </div>
      </div>
    <% end %>

</div>

app/views/dogs/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Editar Cão</h1>

<%= render 'form', dog: @dog %>

app/views/dogs/index.html.erb
<div class="row">
    <% @dogs.each do |dog| %>
      <div class = "col l3 m6 s12">
          <div class= "card">
            <div class= "card-image">
              <% if dog.image.present? %>
                <%= link_to image_tag(dog.image_url(:thumb).to_s), dog %>
              <% else %>
                 <%= link_to image_tag('logo.png', size:"227x227"), dog%>
              <% end %>
            </div>
              <div class="card-content">
                <span class="card-title">
                  <%= dog.name %>
                </span>
                <%= dog.gender %>
                <br>
                <%= dog.breed %>
                <br>
                <strong>Vacinado</strong>
                <%= dog.vacined %>
                <br>
                <strong>Pedigree</strong>
                <%= dog.pedigre %>
              </div>
          </div>
      </div>
    <% end %>

</div>

app/views/dogs/mydogs.html.erb
<div class="row">
    <% @dogs.each do |dog| %>
      <div class="col l3 m6 s12 ">
          <div class="card">
            <div class="card-image ">
              <% if dog.image.present? %>
                <%= link_to image_tag(dog.image_url(:thumb).to_s), dog %>
              <% else %>
                 <%= link_to image_tag('logo.png', size:"227x227"),dog%>
              <% end %>
            </div>
              <div class="card-content">
                <span class="card-title">
                  <%= dog.name %>
                </span>
                <%= dog.gender %>
                <br>
                <%= dog.breed %>
            </div>
            <div class="card-action">
              <div class="align center">
                <%= link_to content_tag(:i, 'compare', class: 'material-icons'), dog_compare_path(dog) %>
                <%= link_to content_tag(:i, 'edit', class: 'material-icons'), edit_dog_path(dog) %>
                <%= link_to content_tag(:i, 'delete', class: 'material-icons'),dog, method: :delete, data: {confirm:'Tem Certeza?'} %>
              </div>
            </div>
          </div>
      </div>
    <% end %>
</div>
<div class="row">
  <div class="align right">
    <br>
    <%= link_to content_tag(:i, 'add', class: 'material-icons'), new_dog_path, class: 'btn-floating waves-effect waves-light btn-large blue' %>
  </div>
</div>

app/views/dogs/new.html.erb
<h1>Adicionar Cão</h1>

<%= render 'form', dog: @dog %>

app/views/dogs/show.html.erb
<div class="row">


 </div>
    <div class = "col l4  m12 s12 ">
      <% if @dog.image.present? %>
      <%= image_tag(@dog.image_url(:thumb).to_s) %>
      <% else %>
      <%= image_tag('logo.png',  size: "350x350")%>
      <% end %>
      <% unless current_user.id == @dog.user_id %>
          <p>
            <%= link_to favorite_text, favorites_update_path(dog: @dog), id:'favorite_link', remote: true %>
          </p>
      <% end %>
    </div>

  <div class= "col l4 m12 s12 ">
    <fieldset>
      <legend>Informações sobre o cão</legend>
        <p>
          <strong>Nome</strong>
          <br>
          <%= @dog.name %>
        </p>
        <p>
          <strong>Idade</strong>
          <br>
          <%= @dog.age  %> anos
        </p>
        <p>
          <strong>Raça</strong>
          <br>
          <%= @dog.breed %>
        </p>
        <p>
          <strong>Genero</strong>
          <br>
          <%= @dog.gender  %>
        </p>
        <p>
          <strong>Vacina</strong>
          <br>
          <%= @dog.vacined  %>
        </p>
        <p>
          <strong>Tamanho</strong>
          <br>
          <%= @dog.length  %>
        </p>
        <strong>Tipo de Pelo</strong>
        <br>
        <%= @dog.pelage  %>
      </p>

      <p>
        <strong>Cor do pelo</strong>
        <br>
        <%= @dog.pelage_color  %>
      </p>
      <p>
        <strong>Temperamento</strong>
        <br>
        <%= @dog.temperament  %>
      </p>

      <p>
        <strong>Pedigree</strong>
        <br>
        <%= @dog.pedigre %>
      </p>

      <% if @dog.pedigree == true %>
      <p>
        <strong>Nome da mãe</strong>
        <br>
        <%= @dog.mother_name  %>
      </p>
      <p>
        <strong>Nome do pai</strong>
        <br>
        <%= @dog.father_name  %>
        <% end %>
      </p>
      <p>
        <strong>Registro</strong>
        <br>
        <%= @dog.register %>
      </p>

  </fieldset>
  </div>


  <div class= "col l4 m12 s12 align right  ">
    <fieldset>
      <legend>Informações sobre o dono</legend>
      <p>
        <strong>Nome</strong>
        <br>
        <%= @dog.user.name %>
      </p>
      <p>
        <strong>Estado</strong>
        <br>
        <%= @dog.user.state %>
      </p>
      <p>
        <strong>Cidade</strong>
        <br>
        <%= @dog.user.city %>
      </p>
      <p>
        <strong>Telefone</strong>
        <br>
        <%= @dog.user.phone %>
      </p>
    </fieldset>
  </div>

</div>