config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  resources :dogs

  devise_for :users, :controllers => { registrations: 'users/registrations', sessions: "users/sessions", passwords: 'users/passwords' } do
     get "/", :to => "users/sessions#create"
   end

   authenticated :user do
     root to: "dogs#mydogs"
   end

   unauthenticated :user do
     devise_scope :user do
       get "/" => "home#homepage"
     end
   end

  get 'mydogs', to: 'dogs#mydogs'
  get 'dogs/:id/compare', to: 'dogs#compare', as: :dog_compare
  get 'allfavorites', to: 'dogs#allfavorites'
  get 'advancedsearch', to: 'dogs#advancedsearch'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class=" light-blue darken-4">
  <div class="container">
    <div class="nav-wrapper">
        <a href="#" class="brand-logo"> <%= image_tag('logo.png', size:"45x45")%> </a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%=link_to "Entrar", new_user_session_path %></li>
        <li><%=link_to "Registrar", new_user_registration_path %></li>
      </ul>
    </div>
  </nav>
  <ul class="sidenav" id="mobile-demo">
    <li><a href="sass.html">Sass</a></li>
    <li><a href="badges.html">Components</a></li>
    <li><a href="collapsible.html">JavaScript</a></li>
  </ul>
</div>

app/views/shared/_navbarTabs.html.erb
<nav class="nav-extended">
   <div class="nav-wrapper">
     <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">Projeto Dog</i></a>

   </div>
   <div class="nav-content">
     <ul class="tabs tabs-transparent">
       <li class="tab"><%=link_to "Ver meus  cães",  mydogs_path %></li>
       <li class="tab"><%=link_to "ver todos os cães", dogs_path %></li>
       <li class="tab"><%=link_to "Favoritos", allfavorites_path %></li>
       <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user.present? %>
           <li><a href="#"> <%= current_user.email %> </a></li>
           <li><%= link_to 'sair',destroy_user_session_path, method: :delete %></li>
           <li><%= link_to 'Editar Usuário', edit_user_registration_path, method: :get %></li>
        <% end %>
       </ul>
     </ul>
   </div>
 </nav>

app/views/shared/_sidenav.html.erb
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<nav class="nav-extended  light-blue darken-4 ">
  <div class="container">
    <div class="nav-wrapper">
      <div class="brand-logo">
        <%= link_to image_tag('logo.png', size:"60x60"), mydogs_path%>
        Projeto
      </div>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user.present? %>
        <li> <i class= "material-icons left">account_circle</i>
          <%= current_user.name %> </li>
          <li><%= link_to content_tag(:i, 'edit', class: 'material-icons'), edit_user_registration_path, method: :get %></li>
          <li> <%= link_to content_tag(:i, 'exit_to_app', class: 'material-icons'),destroy_user_session_path, method: :delete %> </li>
          <% end %>
        </ul>
    </div>
    <div class="nav-contennt " >
      <ul class="tabs tabs-transparent" style="display:flex; justify-content:center;">
        <li class="tab "><%=link_to "Ver meus  cães",  mydogs_path %></li>
        <li class="tab"><%=link_to "ver todos os cães", dogs_path %></li>
        <li class="tab"><%=link_to "Buscar", advancedsearch_path, data: {turbolinks: false } %></li>
        <li class="tab"><%=link_to "Favoritos", allfavorites_path %></li>
      </ul>
    </div>
  </div>
</nav>


  <ul class="sidenav" id="mobile-demo">
  <li>  <%= link_to content_tag(:i, 'edit', class: 'material-icons'), edit_user_registration_path, method: :get %></li>


    <li><%= link_to 'sair',destroy_user_session_path, method: :delete %></li>
  </ul>